Feat/foundation consumer backend
TrubitTech/TrubitTech pull request #18
Opened 2022-05-15 17:14 UTC by vigasdeep

2022-05-16 17:02 UTC, gurjit03 requested changes
Some minor feedback, but looking good and solid overall :)

2022-05-16 17:02 UTC, gurjit03 commented on applications/consumer-backend/utils/constants.ts
> +export const USER = {
what are these utils being referred to ? If it's some constants being used for USER model. I believe the best place is to put these under the module user

2022-05-16 21:37 UTC, joeyfigaro requested changes
Great work, @vigasdeep! Thank you for taking the time to put this together. I marked a bunch of small details and some of them are more discussion prompts for all of us. 

Make sure that you've got your editor configured to use prettier and eslint so you can catch linting issues while you're working, as well:
https://joeysharesthings.com/xVpumP
https://joeysharesthings.com/VMk5PP
https://joeysharesthings.com/yzSFW3

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/package.json
> +    "tslint": "^6.1.3",
swap all `tslint*` dependencies for their eslint counterparts–can help with this if needed

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/modules/user/userModel.ts
> +const userSchema: Schema = new Schema({
I'm assuming that the omission of id was intentional here (it has been a long time since I worked with nosql/mongo)–but we shouldn't store any of this info. I think to start we can just specify a `did` property for decentralized identifiers.

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/modules/user/userController.ts
> +  User
Second that!

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/modules/user/userController.ts
> +    res.status(StatusCodes.NOT_FOUND).json(getReasonPhrase(StatusCodes.NOT_FOUND))
We should use typed return payloads for all of our responses–maybe something like the following:

```ts
interface OperationResponse {
  ok: boolean
  data?: Record<string, unknown>
  error?: {
    code: string;
    message: string;
  }
}

interface OperationErrorResponse extends OperationResponse {
  ok: false
  data: never
  error: {
    code: string
    message: string
  }
}

interface OperationSuccessResponse extends OperationResponse {
  ...
}

// error response
{
  ok: false,
  status: 500,
  error: {
    code: 'UH_OH_NO_GOOD',
    message: 'Whoop. Something exploded.'
  }
}

// successful response
{
  ok: true,
  status: 200,
  data: {
    id: 123
  } 
}

```

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/middlewares/notFoundErrorHandler.ts
> +  return res.status(StatusCodes.NOT_FOUND).json({
See note below about using shared / typed responses 💯

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/server.ts
> +app.use('/auth', userRoutes);
what do you think of using the module's focus/identifier as the base path here? e.g.

```ts
app.use('/user', userRoutes)
```

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/server.ts
> +  res.send('Consumer Backend API');
See note below about shared / typed responses

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/server.ts
> +export default app;
Unless I'm outvoted, I'd prefer we avoid default exports–they make debugging more difficult and make for a poorer development experience since they're unnamed

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/utils/logger/morgan.ts
> +const morgan = require('morgan');
stick with `import` for pulling packages in

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/utils/logger/morgan.ts
> +require('dotenv').config();
move dotenv initialization to root of API (prior to any module imports/execution)

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/utils/constants.ts
> +export const USER = {
since we aren't using these constants, we might as well remove this and wait until we actually need them. unsure if we'll find ourselves needing constants across multiple modules, which would make putting them inside individual modules hairy

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/tslint.json
> +{
can remove this tslint config in favor of prettier/eslint config set up for monorepo

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/package.json
> +    "tslint": "^6.1.3",
For any dependencies that are already specified in the root package.json (for the whole monorepo) you can use `*` to grab whatever copy is available. Typically you'll want to specify the version in the root package.json and use `*` in all workspace packages that also need it to keep dependencies at a consistent starting point

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/modules/user/userRoutes.ts
> +export default userRouter;
See note about default exports

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/modules/user/userRoutes.ts
> +userRouter.post('/create-user', userController.create);
If we do end up using module names for base paths, we should consider/discuss using actions for endpoints:

`/auth/create-user` -> `/user/create` 

Or even rely on request method:

```
- /users
  - POST (create)
  - DELETE (delete)
  - PATCH (update)
  - GET (get all users) 
 ```

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/server.ts
> +require('dotenv').config();
this should come before any module imports

2022-05-16 21:37 UTC, joeyfigaro commented on applications/consumer-backend/server.ts
> +app.set('port', process.env.PORT || 3000);
use your environment variables module for setting these 💪🏻

2022-05-27 03:17 UTC, vigasdeep commented on applications/consumer-backend/modules/user/userController.ts
> +  if(!req.body){
fixed!

2022-05-27 03:17 UTC, vigasdeep commented on applications/consumer-backend/modules/user/userController.ts
> +  User
resolved

2022-05-27 03:18 UTC, vigasdeep commented on applications/consumer-backend/server.ts
> +mongo.init();
right. I've removed mongo related code

2022-05-27 03:22 UTC, vigasdeep commented on applications/consumer-backend/modules/user/userController.ts
> +    res.status(StatusCodes.NOT_FOUND).json(getReasonPhrase(StatusCodes.NOT_FOUND))
all right! kindly let me know it looks now.

2022-05-30 14:23 UTC, joeyfigaro commented on applications/consumer-backend/server.ts
> +mongo.init();
@vigasdeep ended up pushing up changes to help get this rolled out so you can move on, but my thinking here is that we can address storing (and anything related) once we hop onto next milestone. 

I'd rather we implement support for things like storage and design our schema while we're actually building out features that require them–should help us make better choices and help us avoid some reworking.

2022-06-02 20:02 UTC, merged